# API specification
api:
  name: "${api.name}"
  version: "${project.version}"
  #Replace with respective autodiscovery id
  autodiscoveryID: "16422492"
 
# Listener configuration 
https:
  host: "0.0.0.0"
  port: "8082"

# API Configurations
case-prc-api: 
  http-listener:
    path: "/api/*"
  #http-client:
   #client-id: "Client Id overridden at deploy time"
   #client-secret: "Client Secret overridden at deploy time"   
  
# SNOW System API Configurations
snow-sys-api: 
  base-path: "/"
  http-reconnection-attempts: "2"
  connection-idle-timeout: "3000"
  port: "443"
  content-type: "application/json"
  path: "/api/incident"
  response-timeout: "60000"
  http-frequency: "5000"
  #Replace with respective application hostname
  host: "accel-servicenow-sys-api.us-e2.cloudhub.io"
  
# SFDC System API Configuration
sfdc-sys-api:  
  http-frequency: "5000"
  content-type: "application/json"
  base-path: "/"
  port: "443"
  response-timeout: "60000"
  path: "/api/case/{caseId}"
  connection-idle-timeout: "3000"
  http-reconnection-attempts: "2"
  #Replace with respective application hostname
  host: "accel-salesforce-sys-api.us-e2.cloudhub.io"
  
# JIRA System API Configuration
jira-sys-api: 
  connection-idle-timeout: "3000"
  # Replace the respective JIRA Project Key Used
  project-key: "SSC"
  port: "443"
  path: "/api/issue"
  http-frequency: "5000"
  base-path: "/"
  http-reconnection-attempts: "2"
  content-type: "application/json"
  # Replace with respective application hostname
  host: "accel-jira-sys-api.us-e2.cloudhub.io"
  response-timeout: "60000"
  
# Retry configuration
retry:
   http: 
    delayMillisecs: "3000"
    numRetries: "3"
    
# Customize the application messages in the below section
application-msgs: 
  # JIRA Issue create success message
  jira-create-success-message:  "Issue Created Successfully"
  success-msg: "Success"
  # No Route Matching Message
  no-match-route-found: "No Matching Route Found"
  # Before Connector logger message
  before-connector-call-message: "Before Connector Call"
  # After Connector logger message
  after-connector-call-message:  "After Connector Call"
  # SNOW Incident create success message
  incident-create-success-message: "Incident Created Successfully"
