# use this file for encrypted user/password information.
# Unencrypted values may be used in this file using standard yaml syntax
# Encrypted values must be enclosed in ![] within the quotes.

case-prc-api:
  http-client:
    client-id: "![DaPFpmc6y6I=]"
    client-secret: "![urMuVYSw+5M=]"
