%dw 2.0
output application/json
---
{
  
  "caseId":"5003k00000zT3sTAAS",
  "caseNumber":"",
  "caseOrigin":"",
  "caseOwner":"",
  "caseReason":"",  
  "contactName":"",
  "type":"", 
  "subject":"",
  "active": "false",
  "activityDue": "",
  "additionalAssigneeList": "",
  "approval": "",
  "approvalHistory": "",
  "approvalSet": "",
  "assignedTo": "",
  "assignedGroup": "",
  "businessDuration": "",
  "businessService": "",
  "businessStc": "",
  "calendarDuration": "",
  "calendarStc": "0",
  "callerId": "",
  "category": "",
  "causedBy": "",
  "childIncidents": "",
  "closeNotes": "",
  "closeCode": "",
  "closedAt": "",
  "closedBy": "",
  "cmdbCi": "",
  "comments": "This is from MUNIT",
  "commentsAndWorkNotes": "",
  "company": "",
  "contactType": "",
  "correlationDisplay": "",
  "correlationId": "",
  "deliveryPlan": "",
  "deliveryTask": "",
  "description": "",
  "dueDate": "",
  "escalation": "",
  "expectedStart": "",
  "followUp": "",
  "groupList": "",
  "holdReason": "",
  "impact": "",
  "incident_state": "0",
  "knowlegde": "false",
  "location": "",
  "madeSla": "false",
  "notify": "0",
  "number": "",
  "openedAt": "",
  "openedBy": "",
  "order": "0",
  "parent": "",
  "parentIncident": "",
  "priority": "0",
  "problemId": "",
  "reassignmentCount": "0",
  "reopenCount": "0",
  "reopenedBy": "",
  "reopenedTime": "",
  "resolvedAt": "",
  "resolvedBy": "",
  "rfc": "",
  "severity": "0",
  "shortDescription": "This is a test incident",
  "slaDue": "",
  "state": "New",
  "subCategory": "",
  "timeWorked": "",
  "uponApproval": "",
  "uponReject": "",
  "urgency": "0",
  "userInput": "",
  "watchList": "",
  "workEnd": "",
  "workNotes": "",
  "workNotesList": "",
  "workStart": "",
  "source": "SNOW",
  "status": "New",
  "owner": "Albert",
  "lastUpdatedDate":"2017-07-21T17:32:28Z",
  "externalComments": "From MUNIT",
  "externalStatus": "In Progress",
  "externalSystemLastUpdated": "10/21/2019",
  "externalOwner":"Latest Update",
  "externalPriority":"1"
   
}