
%dw 2.0
output application/json
---
{   
	
	caseId:"5003k00000zSbwPAAS",
	syncToSNOW : "true",
	comments: "This is from MUnit",
//	active:  "",
//	activityDue:  "",
//	additionalAssigneeList:  "",
//	approval:  "",
//	approvalHistory:  "",
//	approvalSet:  "",
//	assignedTo:  "",
//	assignedGroup:  "",
//	businessDuration:  "",
//	businessService:  "",
//	businessStc: "",
//	calendarDuration:  "",
//	calendarStc:  "",
//	callerId:  "",
//	category:  "",
//	causedBy:  "",
//	childIncidents:  "",
//	closeNotes:  "Test",
//	closeCode:  "Test",
//	closedAt: "",
//	closedBy:  "",
//	cmdbCi:  "",
   
//	commentsAndWorkNotes:  "",
//	company: "",
//	contactType: "",
//	correlationDisplay:  "",
//	correlationId: "",
//	deliveryPlan:  "",
//	deliveryTask:  "",
//	description:  "",
//	dueDate:  "",
//	escalation:  "",
//	expectedStart: "",
//	followUp: "",
//	groupList:  "",
//	holdReason:  "",
//	impact:  "",
//	incident_state:  "",
//	knowlegde:  "",
//	location: "",
//	madeSla: "",
//	notify: "",
//	number: "",
//	openedAt:  "",
//	openedBy: "",
//	order: "",
//	parent:  "",
//	parentIncident:  "",
    priority:  "Medium",
//	problemId:  "",
//	reassignmentCount:  "",
//	reopenCount:   "",
//	reopenedBy:  "",
//	reopenedTime:  "",
//	resolvedAt:  "",
//	resolvedBy:  "",
//	rfc:  "",
//	severity:  "",
    subject:"Testing From MUnit Process API",
//	slaDue: "",
//	state: "New" ,
//	subCategory:  "",
//	timeWorked: "",
//	uponApproval:  "",
//	uponReject: "",
//	urgency:  "",
//	userInput:  "",
//	watchList:  "",
//	workEnd: "",
//	workNotes:  "",
//	workNotesList:  "",
//	workStart: ""
}